name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]   # Run workflow when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3   # Checkout your repo
      - name: Push to Hugging Face Space
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"
          git remote add space https://huggingface.co/spaces/<username>/<space-name>
          git push https://huggingface.co/${{ secrets.HF_TOKEN }}@huggingface.co/spaces/<username>/<space-name> main --force
